// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Packet.proto

package com.yealink.im.protocol;

public final class Packet {
  private Packet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.yealink.im.protocol.PacketType}
   */
  public enum PacketType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REQ = 0;</code>
     */
    REQ(0),
    /**
     * <code>RESP = 1;</code>
     */
    RESP(1),
    /**
     * <code>NOTIFY = 2;</code>
     */
    NOTIFY(2),
    ;

    /**
     * <code>REQ = 0;</code>
     */
    public static final int REQ_VALUE = 0;
    /**
     * <code>RESP = 1;</code>
     */
    public static final int RESP_VALUE = 1;
    /**
     * <code>NOTIFY = 2;</code>
     */
    public static final int NOTIFY_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PacketType valueOf(int value) {
      return forNumber(value);
    }

    public static PacketType forNumber(int value) {
      switch (value) {
        case 0: return REQ;
        case 1: return RESP;
        case 2: return NOTIFY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PacketType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PacketType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PacketType>() {
            public PacketType findValueByNumber(int number) {
              return PacketType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.yealink.im.protocol.Packet.getDescriptor().getEnumTypes().get(0);
    }

    private static final PacketType[] VALUES = values();

    public static PacketType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PacketType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.yealink.im.protocol.PacketType)
  }

  /**
   * Protobuf enum {@code com.yealink.im.protocol.CmdID}
   */
  public enum CmdID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *群组创建
     * </pre>
     *
     * <code>GROUP_CREATE = 12289;</code>
     */
    GROUP_CREATE(12289),
    /**
     * <pre>
     *单对单聊天
     * </pre>
     *
     * <code>SINGLE_CHAT = 8193;</code>
     */
    SINGLE_CHAT(8193),
    ;

    /**
     * <pre>
     *群组创建
     * </pre>
     *
     * <code>GROUP_CREATE = 12289;</code>
     */
    public static final int GROUP_CREATE_VALUE = 12289;
    /**
     * <pre>
     *单对单聊天
     * </pre>
     *
     * <code>SINGLE_CHAT = 8193;</code>
     */
    public static final int SINGLE_CHAT_VALUE = 8193;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CmdID valueOf(int value) {
      return forNumber(value);
    }

    public static CmdID forNumber(int value) {
      switch (value) {
        case 12289: return GROUP_CREATE;
        case 8193: return SINGLE_CHAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CmdID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CmdID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CmdID>() {
            public CmdID findValueByNumber(int number) {
              return CmdID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.yealink.im.protocol.Packet.getDescriptor().getEnumTypes().get(1);
    }

    private static final CmdID[] VALUES = values();

    public static CmdID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CmdID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.yealink.im.protocol.CmdID)
  }

  public interface PacketsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yealink.im.protocol.Packets)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     *发送者jid
     * </pre>
     *
     * <code>required string from = 2;</code>
     */
    boolean hasFrom();
    /**
     * <pre>
     *发送者jid
     * </pre>
     *
     * <code>required string from = 2;</code>
     */
    java.lang.String getFrom();
    /**
     * <pre>
     *发送者jid
     * </pre>
     *
     * <code>required string from = 2;</code>
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <pre>
     *接收者jid
     * </pre>
     *
     * <code>optional string to = 3;</code>
     */
    boolean hasTo();
    /**
     * <pre>
     *接收者jid
     * </pre>
     *
     * <code>optional string to = 3;</code>
     */
    java.lang.String getTo();
    /**
     * <pre>
     *接收者jid
     * </pre>
     *
     * <code>optional string to = 3;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>required .com.yealink.im.protocol.PacketType type = 4;</code>
     */
    boolean hasType();
    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>required .com.yealink.im.protocol.PacketType type = 4;</code>
     */
    com.yealink.im.protocol.Packet.PacketType getType();

    /**
     * <pre>
     *command id
     * </pre>
     *
     * <code>required .com.yealink.im.protocol.CmdID cmd = 5;</code>
     */
    boolean hasCmd();
    /**
     * <pre>
     *command id
     * </pre>
     *
     * <code>required .com.yealink.im.protocol.CmdID cmd = 5;</code>
     */
    com.yealink.im.protocol.Packet.CmdID getCmd();
  }
  /**
   * Protobuf type {@code com.yealink.im.protocol.Packets}
   */
  public  static final class Packets extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.yealink.im.protocol.Packets)
      PacketsOrBuilder {
    // Use Packets.newBuilder() to construct.
    private Packets(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packets() {
      id_ = "";
      from_ = "";
      to_ = "";
      type_ = 0;
      cmd_ = 12289;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packets(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              from_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              to_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.yealink.im.protocol.Packet.PacketType value = com.yealink.im.protocol.Packet.PacketType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                type_ = rawValue;
              }
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.yealink.im.protocol.Packet.CmdID value = com.yealink.im.protocol.Packet.CmdID.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                cmd_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yealink.im.protocol.Packet.internal_static_com_yealink_im_protocol_Packets_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yealink.im.protocol.Packet.internal_static_com_yealink_im_protocol_Packets_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yealink.im.protocol.Packet.Packets.class, com.yealink.im.protocol.Packet.Packets.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROM_FIELD_NUMBER = 2;
    private volatile java.lang.Object from_;
    /**
     * <pre>
     *发送者jid
     * </pre>
     *
     * <code>required string from = 2;</code>
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *发送者jid
     * </pre>
     *
     * <code>required string from = 2;</code>
     */
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          from_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *发送者jid
     * </pre>
     *
     * <code>required string from = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 3;
    private volatile java.lang.Object to_;
    /**
     * <pre>
     *接收者jid
     * </pre>
     *
     * <code>optional string to = 3;</code>
     */
    public boolean hasTo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *接收者jid
     * </pre>
     *
     * <code>optional string to = 3;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          to_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *接收者jid
     * </pre>
     *
     * <code>optional string to = 3;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>required .com.yealink.im.protocol.PacketType type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>required .com.yealink.im.protocol.PacketType type = 4;</code>
     */
    public com.yealink.im.protocol.Packet.PacketType getType() {
      com.yealink.im.protocol.Packet.PacketType result = com.yealink.im.protocol.Packet.PacketType.valueOf(type_);
      return result == null ? com.yealink.im.protocol.Packet.PacketType.REQ : result;
    }

    public static final int CMD_FIELD_NUMBER = 5;
    private int cmd_;
    /**
     * <pre>
     *command id
     * </pre>
     *
     * <code>required .com.yealink.im.protocol.CmdID cmd = 5;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *command id
     * </pre>
     *
     * <code>required .com.yealink.im.protocol.CmdID cmd = 5;</code>
     */
    public com.yealink.im.protocol.Packet.CmdID getCmd() {
      com.yealink.im.protocol.Packet.CmdID result = com.yealink.im.protocol.Packet.CmdID.valueOf(cmd_);
      return result == null ? com.yealink.im.protocol.Packet.CmdID.GROUP_CREATE : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, from_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, to_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, type_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, cmd_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, from_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, to_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, cmd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yealink.im.protocol.Packet.Packets)) {
        return super.equals(obj);
      }
      com.yealink.im.protocol.Packet.Packets other = (com.yealink.im.protocol.Packet.Packets) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasFrom() == other.hasFrom());
      if (hasFrom()) {
        result = result && getFrom()
            .equals(other.getFrom());
      }
      result = result && (hasTo() == other.hasTo());
      if (hasTo()) {
        result = result && getTo()
            .equals(other.getTo());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasCmd() == other.hasCmd());
      if (hasCmd()) {
        result = result && cmd_ == other.cmd_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasFrom()) {
        hash = (37 * hash) + FROM_FIELD_NUMBER;
        hash = (53 * hash) + getFrom().hashCode();
      }
      if (hasTo()) {
        hash = (37 * hash) + TO_FIELD_NUMBER;
        hash = (53 * hash) + getTo().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasCmd()) {
        hash = (37 * hash) + CMD_FIELD_NUMBER;
        hash = (53 * hash) + cmd_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yealink.im.protocol.Packet.Packets parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yealink.im.protocol.Packet.Packets parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yealink.im.protocol.Packet.Packets parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yealink.im.protocol.Packet.Packets parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yealink.im.protocol.Packet.Packets parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yealink.im.protocol.Packet.Packets parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yealink.im.protocol.Packet.Packets parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yealink.im.protocol.Packet.Packets parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yealink.im.protocol.Packet.Packets parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yealink.im.protocol.Packet.Packets parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yealink.im.protocol.Packet.Packets prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yealink.im.protocol.Packets}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yealink.im.protocol.Packets)
        com.yealink.im.protocol.Packet.PacketsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yealink.im.protocol.Packet.internal_static_com_yealink_im_protocol_Packets_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yealink.im.protocol.Packet.internal_static_com_yealink_im_protocol_Packets_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yealink.im.protocol.Packet.Packets.class, com.yealink.im.protocol.Packet.Packets.Builder.class);
      }

      // Construct using com.yealink.im.protocol.Packet.Packets.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        to_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        cmd_ = 12289;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yealink.im.protocol.Packet.internal_static_com_yealink_im_protocol_Packets_descriptor;
      }

      public com.yealink.im.protocol.Packet.Packets getDefaultInstanceForType() {
        return com.yealink.im.protocol.Packet.Packets.getDefaultInstance();
      }

      public com.yealink.im.protocol.Packet.Packets build() {
        com.yealink.im.protocol.Packet.Packets result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yealink.im.protocol.Packet.Packets buildPartial() {
        com.yealink.im.protocol.Packet.Packets result = new com.yealink.im.protocol.Packet.Packets(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.to_ = to_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.cmd_ = cmd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yealink.im.protocol.Packet.Packets) {
          return mergeFrom((com.yealink.im.protocol.Packet.Packets)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yealink.im.protocol.Packet.Packets other) {
        if (other == com.yealink.im.protocol.Packet.Packets.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasFrom()) {
          bitField0_ |= 0x00000002;
          from_ = other.from_;
          onChanged();
        }
        if (other.hasTo()) {
          bitField0_ |= 0x00000004;
          to_ = other.to_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasFrom()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        if (!hasCmd()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yealink.im.protocol.Packet.Packets parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yealink.im.protocol.Packet.Packets) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object from_ = "";
      /**
       * <pre>
       *发送者jid
       * </pre>
       *
       * <code>required string from = 2;</code>
       */
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *发送者jid
       * </pre>
       *
       * <code>required string from = 2;</code>
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            from_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送者jid
       * </pre>
       *
       * <code>required string from = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送者jid
       * </pre>
       *
       * <code>required string from = 2;</code>
       */
      public Builder setFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者jid
       * </pre>
       *
       * <code>required string from = 2;</code>
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者jid
       * </pre>
       *
       * <code>required string from = 2;</code>
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <pre>
       *接收者jid
       * </pre>
       *
       * <code>optional string to = 3;</code>
       */
      public boolean hasTo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *接收者jid
       * </pre>
       *
       * <code>optional string to = 3;</code>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            to_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收者jid
       * </pre>
       *
       * <code>optional string to = 3;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收者jid
       * </pre>
       *
       * <code>optional string to = 3;</code>
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者jid
       * </pre>
       *
       * <code>optional string to = 3;</code>
       */
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者jid
       * </pre>
       *
       * <code>optional string to = 3;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        to_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>required .com.yealink.im.protocol.PacketType type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>required .com.yealink.im.protocol.PacketType type = 4;</code>
       */
      public com.yealink.im.protocol.Packet.PacketType getType() {
        com.yealink.im.protocol.Packet.PacketType result = com.yealink.im.protocol.Packet.PacketType.valueOf(type_);
        return result == null ? com.yealink.im.protocol.Packet.PacketType.REQ : result;
      }
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>required .com.yealink.im.protocol.PacketType type = 4;</code>
       */
      public Builder setType(com.yealink.im.protocol.Packet.PacketType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>required .com.yealink.im.protocol.PacketType type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        onChanged();
        return this;
      }

      private int cmd_ = 12289;
      /**
       * <pre>
       *command id
       * </pre>
       *
       * <code>required .com.yealink.im.protocol.CmdID cmd = 5;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *command id
       * </pre>
       *
       * <code>required .com.yealink.im.protocol.CmdID cmd = 5;</code>
       */
      public com.yealink.im.protocol.Packet.CmdID getCmd() {
        com.yealink.im.protocol.Packet.CmdID result = com.yealink.im.protocol.Packet.CmdID.valueOf(cmd_);
        return result == null ? com.yealink.im.protocol.Packet.CmdID.GROUP_CREATE : result;
      }
      /**
       * <pre>
       *command id
       * </pre>
       *
       * <code>required .com.yealink.im.protocol.CmdID cmd = 5;</code>
       */
      public Builder setCmd(com.yealink.im.protocol.Packet.CmdID value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *command id
       * </pre>
       *
       * <code>required .com.yealink.im.protocol.CmdID cmd = 5;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cmd_ = 12289;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.yealink.im.protocol.Packets)
    }

    // @@protoc_insertion_point(class_scope:com.yealink.im.protocol.Packets)
    private static final com.yealink.im.protocol.Packet.Packets DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yealink.im.protocol.Packet.Packets();
    }

    public static com.yealink.im.protocol.Packet.Packets getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Packets>
        PARSER = new com.google.protobuf.AbstractParser<Packets>() {
      public Packets parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Packets(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packets> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packets> getParserForType() {
      return PARSER;
    }

    public com.yealink.im.protocol.Packet.Packets getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yealink_im_protocol_Packets_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yealink_im_protocol_Packets_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017IM.Packet.proto\022\027com.yealink.im.protoc" +
      "ol\"\217\001\n\007Packets\022\n\n\002id\030\001 \002(\t\022\014\n\004from\030\002 \002(\t" +
      "\022\n\n\002to\030\003 \001(\t\0221\n\004type\030\004 \002(\0162#.com.yealink" +
      ".im.protocol.PacketType\022+\n\003cmd\030\005 \002(\0162\036.c" +
      "om.yealink.im.protocol.CmdID*+\n\nPacketTy" +
      "pe\022\007\n\003REQ\020\000\022\010\n\004RESP\020\001\022\n\n\006NOTIFY\020\002*,\n\005Cmd" +
      "ID\022\021\n\014GROUP_CREATE\020\201`\022\020\n\013SINGLE_CHAT\020\201@B" +
      "\010B\006Packet"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_yealink_im_protocol_Packets_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yealink_im_protocol_Packets_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yealink_im_protocol_Packets_descriptor,
        new java.lang.String[] { "Id", "From", "To", "Type", "Cmd", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
